/**
 * Dados de Treinamento do NEXO
 *
 * Este arquivo contém os exemplos de treinamento para o classificador
 * neural do NEXO. Cada intenção possui múltiplas variações em português
 * brasileiro para garantir robustez na classificação.
 *
 * COMO ADICIONAR NOVOS EXEMPLOS:
 * 1. Identifique a intenção correta (ou crie nova)
 * 2. Adicione variações naturais em PT-BR
 * 3. Execute `pnpm train:nexo` para re-treinar
 *
 * Dados de Treinamento do NEXO v2.0 - COMPATÍVEL
 *
 * ✅ 3x mais exemplos (350 → 1000+)
 * ✅ Typos, gírias, contexto
 *
 * MELHORIAS v2.0:
 * - 3x mais exemplos por intent
 * - Variações com erros de digitação
 * - Gírias e expressões regionais (CE/Nordeste)
 * - Contexto de plataformas (Netflix, cinema, etc)
 * - Casos extremos cobertos
 */

export interface TrainingExample {
	text: string;
	intent: string;
}

export interface TrainingIntent {
	intent: string;
	action: string;
	examples: string[];
	answers?: string[];
}

/**
 * Dados de treinamento organizados por intenção
 */
export const NEXO_TRAINING_DATA: TrainingIntent[] = [
	// =========================================================================
	// SAUDAÇÕES E CONVERSA CASUAL
	// =========================================================================
	{
		intent: 'greetings.hello',
		action: 'greet',
		examples: [
			'oi',
			'olá',
			'ola',
			'hey',
			'hi',
			'hello',
			'e aí',
			'eae',
			'opa',
			'fala',
			'fala aí',
			'fala brother',
			'fala mano',
			'fala parceiro',
			'salve',
			'salve salve',
			'bom dia',
			'boa tarde',
			'boa noite',
			'oi, tudo bem?',
			'oi tudo bem',
			'olá, como vai?',
			'hey, beleza?',
			'e aí, beleza?',
			'tudo certo?',
			'tudo tranquilo?',
			'tudo bem contigo?',
			'como vai?',
			'como está?',
			'tudo certo',
			'tudo na paz?',
			'oxe, e aí?',
			'vixe maria',
			'ô meu rei',
			'e aí cabra',
			'salve meu chapa',
			'oii',
			'oie',
			'oi oi',
			'oiii',
			'eai',
			'eaee',
			'coé',
			'qualé',
			'suave?',
			'firmeza?',
			'tranquilo?',
		],
		answers: [
			'Oi! 👋',
			'Olá! 👋',
			'E aí! 👋',
			'Opa! 👋',
			'Salve! 👋',
			'Firmeza! 👋',
		],
	},
	{
		intent: 'greetings.bye',
		action: 'farewell',
		examples: [
			'tchau',
			'tchau tchau',
			'até mais',
			'até logo',
			'até',
			'até breve',
			'até a próxima',
			'até amanhã',
			'até depois',
			'falou',
			'flw',
			'flws',
			'vlw',
			'valeu',
			'valeu mano',
			'valeu parceiro',
			'valeu brother',
			'tmj',
			'tmj mano',
			'valeu tmj',
			'obrigado',
			'obrigada',
			'obrigado pela ajuda',
			'muito obrigado',
			'brigadão',
			'obrigadão',
			'brigado',
			'brigada',
			'thanks',
			'obg',
			'vou indo',
			'tenho que ir',
			'to indo',
			'preciso ir',
			'já volto',
			'depois eu volto',
			'vou nessa',
			'é isso',
			'era só isso',
			'por hoje é só',
			'boa noite',
			'bom descanso',
			'até semana que vem',
			'bye',
			'goodbye',
			'see ya',
			'see you',
			'later',
			'tch',
			'xau',
			'xauu',
			'ate mais',
			'flww',
			'é nois',
			'suave na nave',
			'fechou',
			'beleza então',
			'firmeza',
		],
		answers: [
			'Até logo! 👋',
			'Falou! 👋',
			'Tmj! 🤝',
			'Por nada! 😊',
			'Valeu! 👋',
			'É nois! 🤝',
		],
	},

	// =========================================================================
	// CLARIFICAÇÃO DE TIPO (usado durante awaiting_context)
	// =========================================================================
	{
		intent: 'clarification.note',
		action: 'clarify_note',
		examples: [
			'é uma nota',
			'é nota',
			'nota',
			'anotação',
			'lembrete',
			'quero anotar',
			'anota aí',
			'anota isso',
			'anota pra mim',
			'anota ai',
			'é pra anotar',
			'preciso anotar',
			'to querendo anotar',
			'guarda como nota',
			'salva como nota',
			'como nota',
			'tipo nota',
			'é um lembrete',
			'quero como lembrete',
			'lembrete mesmo',
			'como lembrete',
			'tipo lembrete',
			'é só uma ideia',
			'é uma ideia',
			'só um pensamento',
			'uma anotação qualquer',
			'é texto',
			'só texto',
			'notaa',
			'anotaçao',
			'anota ae',
			'lembreti',
		],
	},
	{
		intent: 'clarification.movie',
		action: 'clarify_movie',
		examples: [
			'é um filme',
			'é filme',
			'filme',
			'movie',
			'to falando do filme',
			'to falando de filme',
			'tô falando do filme',
			'tô falando de filme',
			'é sobre o filme',
			'quero como filme',
			'salva como filme',
			'guarda como filme',
			'como filme',
			'tipo filme',
			'filme mesmo',
			'é filme sim',
			'foi filme',
			'era filme',
			'é sim um filme',
			'um filme',
			'vi no cinema',
			'passou no cinema',
			'do cinema',
			'filme de cinema',
			'longa-metragem',
			'longa metragem',
			'longa',
			'tem 2 horas',
			'dura 90 minutos',
			'filme de 2h',
			'não é série',
			'não é série não',
			'série não',
			'filme, não série',
			'filmi',
			'filmee',
			'filme msm',
			'flm',
			'filmão',
			'filmezão',
			'um filmão dahora',
		],
	},
	{
		intent: 'clarification.tv_show',
		action: 'clarify_tv_show',
		examples: [
			'é uma série',
			'é série',
			'série',
			'series',
			'tv show',
			'show',
			'seriado',
			'to falando da série',
			'to falando de série',
			'tô falando da série',
			'tô falando de série',
			'é sobre a série',
			'quero como série',
			'salva como série',
			'guarda como série',
			'como série',
			'tipo série',
			'série mesmo',
			'é série sim',
			'foi série',
			'era série',
			'é sim uma série',
			'uma série',
			'é um seriado',
			'vi na netflix',
			'tá na netflix',
			'da netflix',
			'série da netflix',
			'assisti na hbo',
			'tem na amazon',
			'série do disney+',
			'show do apple tv',
			'tem 3 temporadas',
			'série de 10 episódios',
			'acabou a temporada',
			'saiu episódio novo',
			'não é filme',
			'não é filme não',
			'filme não',
			'série, não filme',
			'seri',
			'sériee',
			'serie msm',
			'srd',
			'seried',
			'seriado top',
			'série dahora',
			'seriado maneiro',
		],
	},
	{
		intent: 'clarification.link',
		action: 'clarify_link',
		examples: [
			'é um link',
			'é link',
			'link',
			'url',
			'site',
			'to falando do link',
			'to falando de link',
			'é um site',
			'é uma url',
			'é uma página',
			'quero como link',
			'salva como link',
			'guarda como link',
			'como link',
			'tipo link',
			'link mesmo',
			'é link sim',
			'foi link',
			'era link',
			'um link',
			'é um artigo',
			'é uma notícia',
			'é um tutorial',
			'página web',
			'site da internet',
			'endereço',
			'linkk',
			'lnk',
			'link msm',
			'sit',
			'urll',
		],
	},
	{
		intent: 'clarification.video',
		action: 'clarify_video',
		examples: [
			'é um vídeo',
			'é vídeo',
			'vídeo',
			'video',
			'é do youtube',
			'vídeo do youtube',
			'link do youtube',
			'do youtube',
			'youtube',
			'yt',
			'to falando do vídeo',
			'é um video',
			'como vídeo',
			'tipo vídeo',
			'vídeo mesmo',
			'é vídeo sim',
			'um vídeo',
			'é um clipe',
			'videoclipe',
			'clip',
			'vlog',
			'tutorial em vídeo',
			'vidio',
			'video msm',
			'vid',
		],
	},

	// =========================================================================
	// SALVAR CONTEÚDO - FILMES
	// =========================================================================
	{
		intent: 'save.movie',
		action: 'save_movie',
		examples: [
			// Padrão básico
			'salva inception',
			'salvar inception',
			'salva o filme inception',
			'salvar o filme matrix',
			'salve inception',
			'adiciona interestelar',
			'adicionar interestelar',
			'add inception',
			'adiciona o filme avatar',
			'guarda inception',
			'guardar inception',
			'guarda o filme avatar',
			'anota inception',
			'anota o filme matrix',
			'anota o poderoso chefão',
			// Quero ver/assistir
			'quero assistir clube da luta',
			'quero ver inception',
			'quero assistir o filme duna',
			'quero ver o filme batman',
			'preciso assistir inception',
			'preciso ver matrix',
			'vou assistir avatar',
			'vou ver interestelar',
			// Lembrar
			'lembra de ver duna',
			'lembra de assistir inception',
			'lembrar de ver matrix',
			'não esquecer de ver avatar',
			'me lembra de assistir coringa',
			// Põe/coloca/bota na lista
			'coloca batman na lista',
			'põe star wars pra eu ver depois',
			'bota pulp fiction',
			'põe inception na lista',
			'coloca na lista o gladiador',
			'bota na lista parasita',
			'põe pra eu ver depois duna',
			'marca inception',
			'marca o senhor dos anéis',
			'marcar inception',
			// Com contexto de cinema
			'vi que inception tá no cinema, salva',
			'passou no cinema aquele filme inception',
			'salva aquele filme que tá em cartaz',
			'o novo filme do nolan, salva',
			'salva aquele longa novo',
			// Com recomendação
			'me recomendaram inception, salva',
			'falaram que inception é bom, guarda',
			'disseram que vale a pena ver matrix',
			'inception é bom, salva aí',
			'joker é muito bom, salva',
			// Especificação explícita
			'quero ver esse filme: oppenheimer',
			'add na lista: top gun maverick',
			'salva esse filme: duna',
			'o filme coringa',
			// Descoberta
			'acabei de descobrir inception',
			'achei um filme chamado matrix',
			'conheci o filme avatar',
			'ouvi falar de interestelar',
			// Filmes famosos
			'salva forrest gump',
			'adiciona parasita',
			'guarda cidade de deus',
			'quero ver tropa de elite',
			'salva velozes e furiosos',
			'add os vingadores',
			'coloca homem aranha',
			'põe harry potter',
			'marca star wars',
			'lembra titanic',
			'guarda jurassic park',
			'salva de volta para o futuro',
			'add o rei leão',
			'coloca toy story',
			// Typos
			'salva incepition',
			'adicona inception',
			'guarda inceptionn',
			'asistir inception',
			'assistir incepção',
			'ver o filme matix',
			'quero ve inception',
			'quero asistir matrix',
			// Gírias
			'mete inception na lista',
			'joga inception aí',
			'cola inception',
			'taca inception',
			'põe essa porra de inception',
			'salva esse filme fodão',
			'filmão, salva aí',
			'esse filme é dahora, guarda',
			// Regionais
			'oxe, salva inception',
			'vixe, guarda esse filme',
			'arretado esse filme, salva',
			'salva esse filme cabra',
			// Temporais
			'vou ver inception amanhã, salva',
			'quero assistir depois',
			'pra ver no fim de semana',
			'assistir na sexta',
			'ver mais tarde',
		],
	},

	// =========================================================================
	// SALVAR CONTEÚDO - SÉRIES/SHOWS
	// =========================================================================
	{
		intent: 'save.tv_show',
		action: 'save_tv_show',
		examples: [
			// Padrão básico
			'salva breaking bad',
			'salvar breaking bad',
			'salva a série breaking bad',
			'salvar a série dark',
			'salve breaking bad',
			'adiciona game of thrones',
			'adicionar stranger things',
			'add breaking bad',
			'adiciona a série the boys',
			'guarda breaking bad',
			'guardar peaky blinders',
			'guarda a série dark',
			'anota breaking bad',
			'anota a série the office',
			'anota série dark',
			// Quero ver/assistir
			'quero assistir the office',
			'quero ver breaking bad',
			'quero assistir a série dark',
			'quero ver a série friends',
			'preciso assistir breaking bad',
			'preciso ver game of thrones',
			'vou assistir stranger things',
			'vou ver the witcher',
			// Lembrar
			'lembra de ver peaky blinders',
			'lembra de assistir dark',
			'lembrar de ver breaking bad',
			'não esquecer de ver the boys',
			'me lembra de assistir wandavision',
			// Põe/coloca/bota na lista
			'coloca friends na lista',
			'põe casa de papel',
			'bota the crown',
			'põe breaking bad na lista',
			'coloca na lista stranger things',
			'bota na lista arcane',
			'põe pra eu ver depois the office',
			'marca the witcher',
			'marca breaking bad',
			'marcar succession',
			// Com contexto de streaming
			'vi que breaking bad tá na netflix, salva',
			'tem na netflix aquela série dark',
			'salva aquela série nova da hbo',
			'a nova série da apple tv, salva',
			'série original netflix, guarda',
			'tá no disney+ aquela série',
			'série da amazon prime',
			'vi no max',
			'tem na paramount+',
			// Com temporadas/episódios
			'série de 5 temporadas, salva',
			'tem 10 episódios só',
			'acabou a temporada de breaking bad',
			'saiu episódio novo de the boys',
			'lançou nova temporada',
			// Com recomendação
			'me recomendaram breaking bad, salva',
			'falaram que dark é boa, guarda',
			'disseram que vale a pena ver the office',
			'breaking bad é muito bom, salva aí',
			'the boys é foda, salva',
			// Especificação explícita
			'quero ver essa série: succession',
			'add na lista de séries: arcane',
			'série recomendada: breaking bad',
			'a série dark',
			'seriado the office',
			// Séries famosas
			'salva the last of us',
			'adiciona the walking dead',
			'guarda westworld',
			'quero ver black mirror',
			'salva stranger things',
			'add the mandalorian',
			'coloca how i met your mother',
			'põe brooklyn nine nine',
			'marca the good place',
			'lembra community',
			'guarda silicon valley',
			'salva mr robot',
			'add narcos',
			'coloca ozark',
			'põe the handmaids tale',
			'salva the umbrella academy',
			'guarda lucifer',
			'add the expanse',
			// Typos
			'salva breacking bad',
			'adicona breaking bad',
			'guarda breaking badd',
			'asistir dark',
			'assistir darck',
			'ver a serie the office',
			'quero ve breaking bad',
			'quero asistir dark',
			'seri breaking bad',
			// Gírias
			'mete breaking bad na lista',
			'joga dark aí',
			'cola the boys',
			'taca stranger things',
			'põe essa porra de breaking bad',
			'salva essa série fodona',
			'seriado top, salva aí',
			'essa série é dahora, guarda',
			// Regionais
			'oxe, salva breaking bad',
			'vixe, guarda essa série',
			'arretada essa série, salva',
			'salva essa série cabra',
			// Temporais
			'vou ver breaking bad amanhã, salva',
			'quero maratonar no fim de semana',
			'pra ver de noite',
			'assistir aos poucos',
			'ver mais tarde',
			'começar essa semana',
		],
	},

	// =========================================================================
	// SALVAR CONTEÚDO - VÍDEOS (YouTube)
	// =========================================================================
	{
		intent: 'save.video',
		action: 'save_video',
		examples: [
			'salva esse vídeo https://youtube.com/watch?v=abc123',
			'salva https://youtube.com/watch?v=abc123',
			'guarda esse link do youtube',
			'adiciona https://youtu.be/xyz',
			'anota esse vídeo pra mim',
			'salva esse vídeo do youtube',
			'guarda esse video https://youtube.com/watch?v=test',
			'add esse vídeo https://www.youtube.com/watch?v=example',
			'coloca esse vídeo na lista',
			'quero ver esse video depois https://youtube.com/watch?v=test',
			'lembra desse vídeo https://www.youtube.com/watch?v=example',
			'quero assistir esse vídeo mais tarde',
			'marca esse vídeo pra eu ver',
			'salva aquele vídeo do YouTube que te mandei',
			'guarda o vídeo',
			'adiciona o vídeo que eu falei',
			'salva esse vídeo',
			'salva aquele vídeo sobre programação',
			'guarda o vídeo do tutorial',
			'adiciona o vídeo da música',
			'salva o clipe',
			'guarda esse videoclipe',
			'salva esse vidio',
			'guarda esse video',
			'adicona esse vídeo',
			'add vid',
			'salva do yt',
			'guarda do youtube',
			'add do yutube',
			'do youtube mesmo',
		],
	},

	// =========================================================================
	// SALVAR CONTEÚDO - LINKS
	// =========================================================================
	{
		intent: 'save.link',
		action: 'save_link',
		examples: [
			'salva esse link https://example.com',
			'salva https://example.com',
			'guarda essa página https://artigo.com/texto',
			'guarda https://site.com.br/noticia',
			'adiciona https://site.com.br/noticia',
			'anota esse site',
			'lembra desse artigo https://medium.com/@user/post',
			'salva a url https://github.com/repo',
			'guarda esse link pra depois',
			'coloca esse link',
			'add https://reddit.com/r/programming',
			'salva esse artigo',
			'guarda essa notícia',
			'adiciona esse tutorial',
			'salva essa documentação',
			'guarda esse blog post',
			'salva essa página',
			'guarda esse site',
			'salva esse link sobre react',
			'guarda essa página de receitas',
			'adiciona esse artigo sobre IA',
			'salva o link do github',
			'guarda o link da documentação',
			'joga esse link aí',
			'mete esse site',
			'bota essa url',
			'cola esse link',
			'salva ese link',
			'guarda ess site',
			'adicona esse link',
			'salva link',
			'salva o link que te mandei',
			'guarda aquele link',
			'adiciona o link',
		],
	},

	// =========================================================================
	// SALVAR CONTEÚDO - NOTAS/LEMBRETES
	// =========================================================================
	{
		intent: 'save.note',
		action: 'save_note',
		examples: [
			'anota: comprar leite',
			'anota comprar leite',
			'lembrete: ligar pro médico',
			'lembrete ligar pro médico',
			'nota: reunião às 15h',
			'nota reunião às 15h',
			'ideia: app de receitas',
			'ideia app de receitas',
			'salva isso: estudar typescript',
			'guarda essa anotação: senha wifi é 12345',
			'salva essa ideia',
			'guarda esse pensamento',
			'anota isso pra mim',
			'lembrar de pagar conta',
			'lembrar: pagar conta',
			'não esquecer: aniversário da mãe',
			'não esquecer de comprar pão',
			'me lembra de ligar',
			'me lembra: dentista amanhã',
			'anotação importante: entregar relatório sexta',
			'pensamento do dia: ser mais produtivo',
			'anotação: comprar presente',
			'pensamento: criar canal no youtube',
			'Aplicativo over screen que conecta no spotify e mostra a letra da música',
			'ideia de negócio: loja de plantas online',
			'ideia: criar bot do telegram',
			'projeto: refatorar código',
			'pensamento: aprender rust',
			'receita de bolo de chocolate',
			'receita: bolo de chocolate',
			'como fazer brigadeiro',
			'passo a passo: instalar linux',
			'preciso comprar presente',
			'tenho que estudar',
			'devo ligar pro banco',
			'fazer exercício',
			'ir ao mercado',
			'dentista quarta às 10h',
			'reunião sexta 15h',
			'senha do wifi: abc123',
			'código do portão: 1234',
			'endereço: rua das flores 123',
			'telefone: 88999998888',
			'bota aí: comprar pão',
			'coloca: estudar',
			'põe: ligar médico',
			'marca: reunião amanhã',
			'anota compra leite',
			'lembrete liga medico',
			'nota reuniao',
			'ideia ap de receitas',
			'lembra de paga conta',
			'oxe, anota: comprar pão',
			'vixe, lembra disso',
			'anota aí cabra',
			'URGENTE: ligar pro cliente',
			'importante: entregar projeto',
			'atenção: reunião cancelada',
			'urgente anota isso',
		],
	},

	// =========================================================================
	// SALVAR CONTEÚDO - CONTEXTO ANTERIOR
	// =========================================================================
	{
		intent: 'save.previous',
		action: 'save_previous',
		examples: [
			'salva',
			'salva aí',
			'salva ai',
			'guarda',
			'guarda aí',
			'guarda ai',
			'salva isso',
			'guarda isso',
			'anota',
			'anota aí',
			'anota ai',
			'anota isso',
			'salva o que eu disse',
			'guarda o que eu falei',
			'salva esse',
			'guarda esse',
			'salva essa',
			'guarda essa',
			'salva o de cima',
			'guarda o que mandei',
			'pode salvar',
			'poderia salvar',
			'pode guardar',
			'poderia guardar',
			'pode adicionar',
			'pode anotar',
			'pode salvar isso',
			'pode guardar pra mim',
			'salva pra mim',
			'guarda pra mim',
			'salva pra depois',
			'guarda pra mais tarde',
			'anota pra mim',
			'bota na lista',
			'coloca na lista',
			'coloca isso na lista',
			'bota isso na lista',
			'adiciona isso',
			'add isso',
			'bota isso',
			'põe isso',
			'põe na lista',
			'salva aí por favor',
			'salva ai pfv',
			'salva pfv',
			'pode guardar por favor',
			'pode guardar pfv',
			'guardar pfv',
			'salvar pfv',
			'anota ai pra mim',
			'anota aí pfv',
			'joga na lista',
			'mete na lista',
			'cola isso',
			'taca aí',
			'salva ae',
			'guarda ae',
			'anota ae',
			'salva isso ai',
			'guard isso',
			'add iso',
			'salva esse filme',
			'guarda essa série',
			'anota esse link',
			'salva essa nota',
			'guarda esse vídeo',
		],
	},

	// =========================================================================
	// BUSCAR/LISTAR CONTEÚDO
	// =========================================================================
	{
		intent: 'search.all',
		action: 'list_all',
		examples: [
			'o que eu salvei',
			'o que salvei',
			'o que tenho salvo',
			'o que tem salvo',
			'meus itens salvos',
			'minha lista',
			'ver minha lista',
			'mostra minha lista',
			'mostra tudo',
			'mostra tudo que salvei',
			'lista tudo',
			'lista tudo que tenho',
			'ver tudo',
			'me mostra tudo',
			'lista meus itens',
			'mostra meus itens',
			'minha coleção',
			'mostra minha coleção',
			'meus salvos',
			'tudo que salvei',
			'tudo salvo',
			'o que tem na minha lista',
			'o que tem aqui',
			'quais itens eu tenho',
			'tem o que salvo',
			'mostra ae',
			'lista ae',
			'me mostra',
			'lista pra mim',
			'mostra pra mim',
			'mostra tudu',
			'lista tud',
			'o q salvei',
			'minha list',
			'mostra minhas fita',
			'mostra o que tem',
			'cadê minha lista',
		],
	},
	{
		intent: 'search.movies',
		action: 'search',
		examples: [
			'mostra meus filmes',
			'mostra filmes',
			'lista os filmes',
			'lista meus filmes',
			'lista filmes',
			'ver meus filmes',
			'ver filmes',
			'me mostra filmes',
			'me mostra meus filmes',
			'filmes salvos',
			'meus filmes salvos',
			'filmes na lista',
			'meus filmes',
			'lista de filmes',
			'quais filmes eu tenho',
			'que filmes eu salvei',
			'quais filmes salvei',
			'tem que filmes',
			'quantos filmes',
			'mostra só filmes',
			'só filmes',
			'filmes apenas',
			'somente filmes',
			'mostra meus filme',
			'lista filme',
			'filmes salvo',
			'meus flm',
			'mostra os filmão',
			'cadê os filmes',
		],
	},
	{
		intent: 'search.tv_shows',
		action: 'search',
		examples: [
			'mostra minhas séries',
			'mostra séries',
			'lista as séries',
			'lista minhas séries',
			'lista séries',
			'ver minhas séries',
			'ver séries',
			'me mostra séries',
			'me mostra minhas séries',
			'séries salvas',
			'minhas séries salvas',
			'séries na lista',
			'minhas séries',
			'lista de séries',
			'quais séries eu tenho',
			'que séries eu salvei',
			'quais séries salvei',
			'tem que séries',
			'quantas séries',
			'mostra só séries',
			'só séries',
			'séries apenas',
			'somente séries',
			'mostra seriados',
			'lista os seriados',
			'mostra minha serie',
			'lista serie',
			'séries salvo',
			'minhas seri',
			'mostra os seriado top',
			'cadê as séries',
		],
	},
	{
		intent: 'search.notes',
		action: 'search',
		examples: [
			'mostra minhas notas',
			'mostra notas',
			'lista as notas',
			'lista minhas notas',
			'lista notas',
			'ver minhas notas',
			'ver notas',
			'me mostra notas',
			'me mostra minhas notas',
			'notas salvas',
			'minhas notas salvas',
			'minhas notas',
			'minhas anotações',
			'lista de notas',
			'lista de lembretes',
			'quais notas eu tenho',
			'que notas eu salvei',
			'quais anotações',
			'tem que notas',
			'quantas notas',
			'mostra só notas',
			'só notas',
			'notas apenas',
			'minhas ideias',
			'mostra ideias',
			'lista lembretes',
			'mostra lembretes',
			'minhas anotações',
			'ver anotações',
			'mostra nota',
			'lista nota',
			'minhas anotaçao',
			'cadê minhas notas',
			'mostra o que anotei',
		],
	},
	{
		intent: 'search.query',
		action: 'search',
		examples: [
			'busca terror',
			'busca ação',
			'procura comédia',
			'pesquisa drama',
			'buscar terror',
			'procurar ação',
			'pesquisar comédia',
			'o que tenho de terror',
			'o que tenho de ação',
			'tem algo de ficção científica',
			'tem algo de comédia',
			'quais filmes de terror',
			'quais séries de drama',
			'busca inception',
			'procura batman',
			'pesquisa matrix',
			'acha stranger things',
			'encontra breaking bad',
			'buscar inception',
			'procurar matrix',
			'pesquisar dark',
			'busca o filme inception',
			'procura a série dark',
			'pesquisa aquele filme batman',
			'acha aquela série the office',
			'tem inception',
			'tenho matrix',
			'tem breaking bad salvo',
			'tenho dark na lista',
			'cade inception',
			'onde ta matrix',
			'acha pra mim dark',
			'busca terro',
			'procura acao',
			'pesquisa comedia',
			'acha incepition',
			'busca filmes de terror',
			'procura séries de ação',
			'pesquisa algo sobre ficção',
		],
	},

	// =========================================================================
	// DELETAR CONTEÚDO
	// =========================================================================
	{
		intent: 'delete.all',
		action: 'delete_all',
		examples: [
			'apaga tudo',
			'apagar tudo',
			'deleta tudo',
			'deletar tudo',
			'remove tudo',
			'remover tudo',
			'exclui tudo',
			'excluir tudo',
			'limpa tudo',
			'limpar tudo',
			'zera a lista',
			'zerar a lista',
			'limpa a lista',
			'limpar lista',
			'apaga toda a lista',
			'deleta toda lista',
			'remove todos',
			'remover todos',
			'exclui todos',
			'excluir todos os itens',
			'apaga todos',
			'deleta todos',
			'apaga td',
			'deleta td',
			'remove td',
			'limpa td',
			'reseta tudo',
			'reseta a parada',
			'zera essa porra',
			'apaga tudu',
			'deleta tudu',
			'limpa tudu',
		],
	},
	{
		intent: 'delete.item',
		action: 'delete_item',
		examples: [
			'apaga inception',
			'apaga o filme inception',
			'deleta matrix',
			'deleta a série matrix',
			'remove batman',
			'remove o filme batman',
			'exclui breaking bad',
			'exclui a série breaking bad',
			'tira inception da lista',
			'tira o filme avatar',
			'remove da lista matrix',
			'remove o filme inception da lista',
			'tira breaking bad',
			'apaga a nota sobre compras',
			'deleta a nota de reunião',
			'remove a anotação sobre estudar',
			'exclui aquela nota',
			'apaga esse inception',
			'deleta essa série dark',
			'remove aquele filme',
			'exclui essa nota',
			'apaga incepition',
			'deleta matix',
			'remove batmam',
			'joga fora inception',
			'descarta matrix',
		],
	},
	{
		intent: 'delete.selection',
		action: 'delete_selected',
		examples: [
			'apaga o 1',
			'apaga o primeiro',
			'apaga a primeira',
			'deleta o 1',
			'deleta o segundo',
			'deleta a segunda',
			'remove o 2',
			'remove o terceiro',
			'remove a terceira',
			'exclui o 3',
			'exclui o quarto',
			'exclui a quarta',
			'apaga o item 2',
			'deleta o item 1',
			'remove o item 3',
			'exclui o item 4',
			'apaga o primeiro item',
			'deleta o segundo item',
			'apaga 1 e 2',
			'apaga o 1 e o 2',
			'deleta 2 e 3',
			'deleta o segundo e o terceiro',
			'remove o primeiro e o terceiro',
			'exclui os filmes 1 e 2',
			'apaga 1, 3 e 5',
			'deleta 1, 2 e 3',
			'remove os itens 1, 2 e 3',
			'deleta as notas 2 e 3',
			'apaga esse',
			'remove essa',
			'deleta esse',
			'exclui essa',
			'apaga esse item',
			'remove esse filme',
			'deleta essa nota',
			'exclui essa série',
			'apaga o de cima',
			'deleta o de baixo',
			'remove o último',
			'exclui o primeiro',
			'remove a série 1',
			'deleta o filme 2',
			'apaga a nota 3',
			'apaga o primero',
			'deleta o segundo',
			'remove o terseiro',
			'apaga 1 e2',
			'deleta item1',
			'apaga um',
			'deleta dois',
			'remove três',
			'exclui quatro',
			'apaga cinco',
		],
	},

	// =========================================================================
	// CONFIRMAÇÃO E NEGAÇÃO
	// =========================================================================
	{
		intent: 'confirmation.yes',
		action: 'confirm',
		examples: [
			'sim',
			's',
			'si',
			'yes',
			'yep',
			'yeah',
			'isso',
			'isso mesmo',
			'isso aí',
			'é isso aí',
			'exato',
			'exatamente',
			'certo',
			'correto',
			'perfeito',
			'perfeitamente',
			'ok',
			'okay',
			'oka',
			'k',
			'beleza',
			'blz',
			'tranquilo',
			'de boa',
			'suave',
			'fechou',
			'pode ser',
			'pode',
			'pode sim',
			'pode salvar',
			'pode confirmar',
			'poderia',
			'confirma',
			'confirmado',
			'confirmo',
			'confirmei',
			'positivo',
			'com certeza',
			'com toda certeza',
			'claro',
			'é claro',
			'claro que sim',
			'óbvio',
			'óbvio que sim',
			'obviamente',
			'lógico',
			'tá certo',
			'tá bom',
			'tá ok',
			'tá tranquilo',
			'ta certo',
			'ta bom',
			'aceito',
			'aceita',
			'aceitar',
			'aceitei',
			'é esse mesmo',
			'é esse',
			'é essa',
			'é essa mesmo',
			'esse mesmo',
			'essa mesma',
			'1',
			'o 1',
			'o primeiro',
			'a primeira',
			'a primeira opção',
			'opção 1',
			'2',
			'o 2',
			'o segundo',
			'a segunda',
			'opção 2',
			'3',
			'o 3',
			'o terceiro',
			'a terceira',
			'opção 3',
			'4',
			'o 4',
			'o quarto',
			'a quarta',
			'5',
			'o 5',
			'o quinto',
			'a quinta',
			'bora',
			'bora lá',
			'partiu',
			'é nois',
			'tmj',
			'fechou mano',
			'ssim',
			'simm',
			'okk',
			'okei',
			'blza',
			'firmza',
		],
	},
	{
		intent: 'confirmation.no',
		action: 'deny',
		examples: [
			'não',
			'nao',
			'n',
			'no',
			'nope',
			'nop',
			'never',
			'cancela',
			'cancelar',
			'cancelado',
			'cancela tudo',
			'cancele',
			'deixa pra lá',
			'deixa',
			'deixa quieto',
			'esquece',
			'esquece isso',
			'esqueça',
			'não quero',
			'não quero não',
			'não preciso',
			'não é isso',
			'não é esse',
			'não é essa',
			'errado',
			'esse não',
			'essa não',
			'negativo',
			'de jeito nenhum',
			'nem pensar',
			'para',
			'para tudo',
			'para isso',
			'pare',
			'parar',
			'desfaz',
			'desfazer',
			'volta',
			'voltar',
			'nenhum',
			'nenhuma',
			'nenhum desses',
			'nenhuma dessas',
			'desiste',
			'desistir',
			'desisti',
			'mudei de ideia',
			'outro',
			'outra',
			'outro não',
			'outra não',
			'claro que não',
			'óbvio que não',
			'jamais',
			'nunca',
			'de forma alguma',
			'não não',
			'nao nao',
			'não é não',
			'interrompe',
			'interromper',
			'para com isso',
			'naum',
			'nn',
			'cancla',
			'nada a ver',
			'tá doido',
			'nem vem',
			'que nada',
		],
	},

	// =========================================================================
	// INFORMAÇÕES DO ASSISTENTE
	// =========================================================================
	{
		intent: 'info.assistant_name',
		action: 'get_assistant_name',
		examples: [
			'qual seu nome',
			'qual é seu nome',
			'qual o seu nome',
			'como você se chama',
			'você tem nome',
			'me fala seu nome',
			'me diz seu nome',
			'seu nome',
			'teu nome',
			'nome',
			'quem é você',
			'quem você é',
			'você é quem',
			'quem tu é',
			'como devo te chamar',
			'como posso te chamar',
			'como te chamam',
			'como te chamo',
			'qual é o nome',
			'qual nome',
			'qual teu nome',
			'como é teu nome',
			'como é seu nome',
			'teu nome é?',
			'seu nome é?',
			'qual teu nome?',
			'qual seu nome?',
			'e seu nome?',
			'nome?',
			'qual se nome',
			'como vc se chama',
			'vc tem nome',
			'qual nome seu',
			'e aí, qual seu nome',
			'me fala como tu chama',
		],
	},
	{
		intent: 'info.help',
		action: 'get_help',
		examples: [
			'o que você faz',
			'o que vc faz',
			'o que tu faz',
			'o que você pode fazer',
			'o que você sabe fazer',
			'quais são suas funções',
			'como funciona',
			'como você funciona',
			'como isso funciona',
			'como que funciona',
			'como usar',
			'como te usar',
			'como te uso',
			'me ajuda',
			'ajuda',
			'help',
			'socorro',
			'preciso de ajuda',
			'pode me ajudar',
			'não entendi',
			'não entendo',
			'não to entendendo',
			'não compreendi',
			'não sei usar',
			'quais são seus comandos',
			'que comandos você tem',
			'comandos disponíveis',
			'o que posso fazer aqui',
			'o que dá pra fazer',
			'tutorial',
			'instruções',
			'manual',
			'guia',
			'como começar',
			'o que é isso',
			'o que é você',
			'pra que serve',
			'qual sua utilidade',
			'como funcion',
			'o q vc faz',
			'oq você faz',
			'me ajud',
			'manda um help aí',
			'explica isso aqui',
			'como é que usa',
		],
	},

	// =========================================================================
	// CONFIGURAÇÕES
	// =========================================================================
	{
		intent: 'settings.change_name',
		action: 'update_settings',
		examples: [
			'quero te chamar de outro nome',
			'quero te chamar de Maria',
			'quero te chamar de João',
			'posso te chamar de Bob',
			'vou te chamar de assistente',
			'te chamo de Bob',
			'muda seu nome',
			'mudar seu nome',
			'muda teu nome',
			'posso mudar seu nome',
			'posso mudar teu nome',
			'altera seu nome',
			'altera teu nome',
			'troca seu nome',
			'seu nome agora é João',
			'teu nome agora é Maria',
			'seu nome é Pedro',
			'te renomeio pra Helper',
			'muda seu nome para Nexinho',
			'altera teu nome pra Carlos',
			'troca seu nome para Ana',
			'te dou o nome de Pedro',
			'posso te dar um nome',
			'posso te dar um apelido',
			'quero dar um nome pra você',
			'posso escolher seu nome',
			'deixa eu escolher teu nome',
			'vou dar um nome pra você',
			'renomear você',
			'mudar como te chamo',
			'escolher seu nome',
			'definir seu nome',
			'muda se nome',
			'quero te chama de outro nome',
			'posso muda seu nome',
		],
	},
];

/**
 * Entidades nomeadas (Named Entities) para extração
 */
export const NEXO_ENTITIES = {
	// Tipos de conteúdo
	item_type: [
		{
			value: 'movie',
			synonyms: ['filme', 'filmes', 'movie', 'movies', 'longa', 'longa-metragem', 'filmão', 'filminho'],
		},
		{
			value: 'tv_show',
			synonyms: [
				'série',
				'séries',
				'series',
				'show',
				'programa',
				'novela',
				'seriado',
				'seriados',
				'minissérie',
				'temporada',
			],
		},
		{
			value: 'video',
			synonyms: ['vídeo', 'vídeos', 'video', 'videos', 'youtube', 'clip', 'clipe', 'yt'],
		},
		{
			value: 'link',
			synonyms: ['link', 'links', 'url', 'site', 'página', 'artigo', 'endereço', 'blog'],
		},
		{
			value: 'note',
			synonyms: ['nota', 'notas', 'anotação', 'anotações', 'lembrete', 'lembretes', 'ideia', 'ideias', 'memo'],
		},
	],

	// Gêneros de filmes/séries (expandido)
	genre: [
		{ value: 'action', synonyms: ['ação', 'acao', 'action', 'aventura'] },
		{ value: 'comedy', synonyms: ['comédia', 'comedia', 'comedy', 'humor', 'engraçado'] },
		{ value: 'drama', synonyms: ['drama', 'dramático', 'dramatico'] },
		{ value: 'horror', synonyms: ['terror', 'horror', 'medo', 'suspense', 'assustador'] },
		{ value: 'scifi', synonyms: ['ficção científica', 'sci-fi', 'scifi', 'ficção', 'ficcao cientifica'] },
		{ value: 'romance', synonyms: ['romance', 'romântico', 'romantico', 'amor'] },
		{ value: 'animation', synonyms: ['animação', 'animacao', 'desenho', 'anime', 'animado'] },
		{ value: 'documentary', synonyms: ['documentário', 'documentario', 'doc', 'documental'] },
		{ value: 'thriller', synonyms: ['thriller', 'suspense'] },
		{ value: 'fantasy', synonyms: ['fantasia', 'fantasy', 'fantasioso'] },
		{ value: 'crime', synonyms: ['crime', 'policial', 'detetive', 'investigação'] },
		{ value: 'western', synonyms: ['western', 'faroeste', 'velho oeste'] },
	],

	// Números ordinais (expandido)
	ordinal: [
		{ value: '1', synonyms: ['primeiro', 'primeira', '1º', '1ª', 'um', 'uma', 'primero'] },
		{ value: '2', synonyms: ['segundo', 'segunda', '2º', '2ª', 'dois', 'duas'] },
		{ value: '3', synonyms: ['terceiro', 'terceira', '3º', '3ª', 'três', 'tres', 'terseiro'] },
		{ value: '4', synonyms: ['quarto', 'quarta', '4º', '4ª', 'quatro'] },
		{ value: '5', synonyms: ['quinto', 'quinta', '5º', '5ª', 'cinco'] },
		{ value: '6', synonyms: ['sexto', 'sexta', '6º', '6ª', 'seis'] },
		{ value: '7', synonyms: ['sétimo', 'sétima', '7º', '7ª', 'sete', 'setimo'] },
		{ value: '8', synonyms: ['oitavo', 'oitava', '8º', '8ª', 'oito'] },
		{ value: '9', synonyms: ['nono', 'nona', '9º', '9ª', 'nove'] },
		{ value: '10', synonyms: ['décimo', 'décima', '10º', '10ª', 'dez', 'decimo'] },
	],

	// Plataformas de streaming
	streaming_platform: [
		{ value: 'netflix', synonyms: ['netflix', 'nflix'] },
		{ value: 'prime', synonyms: ['amazon', 'prime', 'prime video', 'amazon prime'] },
		{ value: 'disney', synonyms: ['disney', 'disney+', 'disney plus'] },
		{ value: 'hbo', synonyms: ['hbo', 'hbo max', 'max'] },
		{ value: 'apple', synonyms: ['apple', 'apple tv', 'apple tv+'] },
		{ value: 'paramount', synonyms: ['paramount', 'paramount+', 'paramount plus'] },
		{ value: 'globoplay', synonyms: ['globoplay', 'globo'] },
	],
};

/**
 * Respostas padrão por intenção (Natural Language Generation)
 */
export const NEXO_RESPONSES: Record<string, string[]> = {
	'greetings.hello': ['Oi! 👋', 'Olá! 👋', 'E aí! 👋', 'Opa! 👋', 'Salve! 👋', 'Firmeza! 👋'],
	'greetings.bye': ['Até logo! 👋', 'Falou! 👋', 'Tmj! 🤝', 'Por nada! 😊', 'Valeu! 👋', 'É nois! 🤝'],
	'info.help': [
		'Posso salvar filmes, séries, vídeos, links e notas pra você! 📚',
		'Me manda o nome de um filme ou série que eu guardo pra você! 🎬',
		'Sou seu assistente pessoal pra organizar conteúdo! Só mandar salvar! 🗂️',
	],
	'confirmation.no': ['Ok, cancelado.', 'Tudo bem, cancelei!', '👌 Cancelado!', 'Beleza, deixa quieto!'],
};