// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/01/2026, 02:36:13
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/srv/projects/nexo/landing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/srv/projects/nexo/landing/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/srv/projects/nexo/landing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/srv/projects/nexo/landing/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/srv/projects/nexo/landing/plugins/**/*.{js,ts,mjs}","/home/srv/projects/nexo/landing/composables/**/*.{js,ts,mjs}","/home/srv/projects/nexo/landing/utils/**/*.{js,ts,mjs}","/home/srv/projects/nexo/landing/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/srv/projects/nexo/landing/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/srv/projects/nexo/landing/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;